// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ColumnMeta 描述结果集的一列。
 */
export class ColumnMeta {
    /**
     * Creates a new ColumnMeta instance.
     * @param {Partial<ColumnMeta>} [$$source = {}] - The source object to create the ColumnMeta.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * Name 列名
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * Type 数据库类型名（驱动提供时填充，否则为空）
             * @member
             * @type {string}
             */
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ColumnMeta}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnMeta(/** @type {Partial<ColumnMeta>} */($$parsedSource));
    }
}

/**
 * ExecuteRequest 描述一次查询请求。
 */
export class ExecuteRequest {
    /**
     * Creates a new ExecuteRequest instance.
     * @param {Partial<ExecuteRequest>} [$$source = {}] - The source object to create the ExecuteRequest.
     */
    constructor($$source = {}) {
        if (!("connId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["connId"] = 0;
        }
        if (!("sqlTemplate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sqlTemplate"] = "";
        }
        if (!("variables" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["variables"] = {};
        }
        if (!("preScript" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["preScript"] = "";
        }
        if (!("postScript" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["postScript"] = "";
        }
        if (!("page" in $$source)) {
            /**
             * Page 页码，从 1 开始；小于等于 0 表示不分页
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            /**
             * PageSize 每页条数；小于等于 0 时取默认值
             * @member
             * @type {number}
             */
            this["pageSize"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * Total 调用方缓存的总数；用于翻页时跳过统计
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("countTotal" in $$source)) {
            /**
             * CountTotal 是否重新统计总数；首次执行与条件变化时应置真
             * @member
             * @type {boolean}
             */
            this["countTotal"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecuteRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExecuteRequest}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("variables" in $$parsedSource) {
            $$parsedSource["variables"] = $$createField2_0($$parsedSource["variables"]);
        }
        return new ExecuteRequest(/** @type {Partial<ExecuteRequest>} */($$parsedSource));
    }
}

/**
 * QueryResult 描述一次查询的完整结果。
 */
export class QueryResult {
    /**
     * Creates a new QueryResult instance.
     * @param {Partial<QueryResult>} [$$source = {}] - The source object to create the QueryResult.
     */
    constructor($$source = {}) {
        if (!("columns" in $$source)) {
            /**
             * Columns 列元信息（保持数据库返回顺序）
             * @member
             * @type {ColumnMeta[]}
             */
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            /**
             * Rows 结果集
             * @member
             * @type {{ [_ in string]?: any }[]}
             */
            this["rows"] = [];
        }
        if (!("sql" in $$source)) {
            /**
             * SQL 实际执行的 SQL，便于用户核对模板渲染结果
             * @member
             * @type {string}
             */
            this["sql"] = "";
        }
        if (!("elapsedMs" in $$source)) {
            /**
             * ElapsedMs 执行耗时
             * @member
             * @type {number}
             */
            this["elapsedMs"] = 0;
        }
        if (!("rowCount" in $$source)) {
            /**
             * RowCount 返回行数
             * @member
             * @type {number}
             */
            this["rowCount"] = 0;
        }
        if (!("truncated" in $$source)) {
            /**
             * Truncated 是否因超出上限被截断
             * @member
             * @type {boolean}
             */
            this["truncated"] = false;
        }
        if (!("total" in $$source)) {
            /**
             * Total 满足条件的数据总量；未分页时等于 RowCount
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            /**
             * Page 当前页码，从 1 开始；未分页时为 1
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            /**
             * PageSize 每页条数；未分页时为 0
             * @member
             * @type {number}
             */
            this["pageSize"] = 0;
        }
        if (!("pageCount" in $$source)) {
            /**
             * PageCount 总页数；未分页时为 1
             * @member
             * @type {number}
             */
            this["pageCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QueryResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        return new QueryResult(/** @type {Partial<QueryResult>} */($$parsedSource));
    }
}

/**
 * TemplateExecuteRequest 描述一次「按模板执行」的请求。
 */
export class TemplateExecuteRequest {
    /**
     * Creates a new TemplateExecuteRequest instance.
     * @param {Partial<TemplateExecuteRequest>} [$$source = {}] - The source object to create the TemplateExecuteRequest.
     */
    constructor($$source = {}) {
        if (!("templateId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["templateId"] = 0;
        }
        if (!("connId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["connId"] = 0;
        }
        if (!("variables" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["variables"] = {};
        }
        if (!("page" in $$source)) {
            /**
             * Page 请求的页码，从 1 开始；仅在模板开启分页时生效
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            /**
             * PageSize 每页条数；小于等于 0 时取模板配置值
             * @member
             * @type {number}
             */
            this["pageSize"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * Total 上一次返回的总数；翻页时带回可避免重复统计
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("countTotal" in $$source)) {
            /**
             * CountTotal 是否重新统计总数；翻页时为 false
             * @member
             * @type {boolean}
             */
            this["countTotal"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemplateExecuteRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TemplateExecuteRequest}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("variables" in $$parsedSource) {
            $$parsedSource["variables"] = $$createField2_0($$parsedSource["variables"]);
        }
        return new TemplateExecuteRequest(/** @type {Partial<TemplateExecuteRequest>} */($$parsedSource));
    }
}

/**
 * TemplateListItem 是模板列表项（含 SQL 预览）。
 */
export class TemplateListItem {
    /**
     * Creates a new TemplateListItem instance.
     * @param {Partial<TemplateListItem>} [$$source = {}] - The source object to create the TemplateListItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("connId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["connId"] = 0;
        }
        if (!("sqlText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sqlText"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemplateListItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TemplateListItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TemplateListItem(/** @type {Partial<TemplateListItem>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = ColumnMeta.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($$createType0);
