/** CREATE TABLE 生成器（元数据 → DDL）；只输出元数据里确实有的东西 */
import type { ExecutorColumn } from '@/types'
import { quoteIdent } from '../rowSql'
import type { SqlDialect } from '../rowSql'

/** 一列的信息（缺省字段表示「元数据没给」，一律不猜） */
export interface CreateTableColumn {
  name: string
  dataType: string
  comment?: string
  nullable?: boolean
  defaultValue?: string
  primaryKey?: boolean
  autoIncrement?: boolean
}

/** 外键定义 */
export interface CreateTableForeignKey {
  column: string
  referencedTable: string
  referencedColumn: string
  referencedSchema?: string
}

/** 建表模型：DDL 生成的全部输入 */
export interface CreateTableModel {
  schema?: string
  tableName: string
  columns: CreateTableColumn[]
  primaryKeys?: string[]
  foreignKeys?: CreateTableForeignKey[]
  /** 表注释 */
  tableComment?: string
  /** 表选项：原样附在末尾 */
  options?: string
}

/** 由连接元数据构造建表模型 */
export function createTableModelOf(source: {
  schema?: string
  tableName: string
  columns: ExecutorColumn[]
}): CreateTableModel {
  return {
    schema: source.schema,
    tableName: source.tableName,
    columns: source.columns.map(column => ({
      name: column.name,
      dataType: column.dataType,
      comment: column.comment || undefined,
    })),
  }
}

/** 单列定义（不含缩进） */
function columnSql(column: CreateTableColumn, dialect: SqlDialect): string {
  const parts = [quoteIdent(column.name, dialect), column.dataType]
  if (column.nullable === false) {
    parts.push('NOT NULL')
  }
  if (column.autoIncrement) {
    // MySQL 是属性，PostgreSQL 用 identity
    if (dialect === 'mysql') {
      parts.push('AUTO_INCREMENT')
    }
    else {
      parts.push('GENERATED BY DEFAULT AS IDENTITY')
    }
  }
  if (column.defaultValue) {
    parts.push(`DEFAULT ${column.defaultValue}`)
  }
  // 行内注释只有 MySQL 有
  if (column.comment && dialect === 'mysql') {
    parts.push(`COMMENT '${column.comment.replace(/'/g, "''")}'`)
  }
  return parts.join(' ')
}

/** 表限定名（带 schema 时限定） */
function tableNameSql(model: CreateTableModel, dialect: SqlDialect): string {
  return [model.schema, model.tableName]
    .filter(Boolean)
    .map(name => quoteIdent(name as string, dialect))
    .join('.')
}

/** MySQL：列内 COMMENT + 表选项 */
function mysqlDdl(model: CreateTableModel): string {
  const lines = model.columns.map(column => `  ${columnSql(column, 'mysql')}`)

  const keys = model.primaryKeys?.length
    ? model.primaryKeys.map(key => quoteIdent(key, 'mysql')).join(', ')
    : ''
  if (keys) {
    lines.push(`  PRIMARY KEY (${keys})`)
  }
  for (const fk of model.foreignKeys ?? []) {
    const target = [fk.referencedSchema, fk.referencedTable]
      .filter(Boolean)
      .map(name => quoteIdent(name as string, 'mysql'))
      .join('.')
    lines.push(`  FOREIGN KEY (${quoteIdent(fk.column, 'mysql')}) REFERENCES ${target} (${quoteIdent(fk.referencedColumn, 'mysql')})`)
  }

  const tail = [
    model.tableComment ? `COMMENT='${model.tableComment.replace(/'/g, "''")}'` : '',
    model.options ?? '',
  ].filter(Boolean).join(' ')

  return `CREATE TABLE ${quoteIdent(model.tableName, 'mysql')} (\n${lines.join(',\n')}\n)${tail ? ` ${tail}` : ''};`
}

/** PostgreSQL：列注释用独立的 COMMENT ON COLUMN */
function postgresDdl(model: CreateTableModel): string {
  const lines = model.columns.map(column => `  ${columnSql(column, 'postgres')}`)

  const keys = model.primaryKeys?.length
    ? model.primaryKeys.map(key => quoteIdent(key, 'postgres')).join(', ')
    : ''
  if (keys) {
    lines.push(`  PRIMARY KEY (${keys})`)
  }
  for (const fk of model.foreignKeys ?? []) {
    const target = [fk.referencedSchema, fk.referencedTable]
      .filter(Boolean)
      .map(name => quoteIdent(name as string, 'postgres'))
      .join('.')
    lines.push(`  FOREIGN KEY (${quoteIdent(fk.column, 'postgres')}) REFERENCES ${target} (${quoteIdent(fk.referencedColumn, 'postgres')})`)
  }

  const statements = [`CREATE TABLE ${tableNameSql(model, 'postgres')} (\n${lines.join(',\n')}\n);`]

  const qualified = tableNameSql(model, 'postgres')
  for (const column of model.columns) {
    if (column.comment) {
      statements.push(`COMMENT ON COLUMN ${qualified}.${quoteIdent(column.name, 'postgres')} IS '${column.comment.replace(/'/g, "''")}';`)
    }
  }
  if (model.tableComment) {
    statements.push(`COMMENT ON TABLE ${qualified} IS '${model.tableComment.replace(/'/g, "''")}';`)
  }
  return statements.join('\n')
}

/** 生成建表语句；列顺序按模型顺序，不重排 */
export function generateCreateTableSql(model: CreateTableModel, dialect: SqlDialect): string {
  if (!model.columns.length) {
    // 没有列信息（元数据未到位）：不输出半截 DDL
    return ''
  }
  return dialect === 'postgres' ? postgresDdl(model) : mysqlDdl(model)
}
