// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * TemplateCheck 模板语法检查结果。
 * 
 * 与 ValidateTemplate 的区别：校验失败时**不报错**，而是把位置与消息作为结果返回，
 * 界面据此在编辑器里标出红色波浪线，而不是弹一个不知道错在哪的提示框。
 */
export class TemplateCheck {
    /**
     * Creates a new TemplateCheck instance.
     * @param {Partial<TemplateCheck>} [$$source = {}] - The source object to create the TemplateCheck.
     */
    constructor($$source = {}) {
        if (!("valid" in $$source)) {
            /**
             * Valid 语法是否通过
             * @member
             * @type {boolean}
             */
            this["valid"] = false;
        }
        if (!("line" in $$source)) {
            /**
             * Line 出错行号（1 起）；拿不到位置时为 0
             * @member
             * @type {number}
             */
            this["line"] = 0;
        }
        if (!("column" in $$source)) {
            /**
             * Column 出错列号（1 起）；拿不到位置时为 0
             * @member
             * @type {number}
             */
            this["column"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * Message 去掉 `template: sql:行:列:` 前缀后的可读信息
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemplateCheck instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TemplateCheck}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TemplateCheck(/** @type {Partial<TemplateCheck>} */($$parsedSource));
    }
}
