// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {services} from '../models';
import {database} from '../models';
import {app} from '../models';

export function BeforeClose(arg1:context.Context):Promise<void>;

export function DeleteConnection(arg1:number):Promise<void>;

export function DeleteDictionary(arg1:number):Promise<void>;

export function DeleteSqlTemplate(arg1:number):Promise<void>;

export function DeleteTemplate(arg1:number):Promise<void>;

export function ExecuteQuery(arg1:services.ExecuteRequest):Promise<services.QueryResult>;

export function ExecuteTemplateQuery(arg1:number,arg2:number,arg3:Record<string, any>):Promise<services.QueryResult>;

export function ExtractTemplateVariables(arg1:string):Promise<Array<string>>;

export function GetAllSettings():Promise<Array<database.Setting>>;

export function GetAppInfo():Promise<app.AppInfo>;

export function GetConnection(arg1:number):Promise<database.DBConnection>;

export function GetSqlTemplate(arg1:number):Promise<database.SQLTemplate>;

export function Greet(arg1:string):Promise<string>;

export function ListConnections():Promise<Array<database.DBConnection>>;

export function ListDictionaries():Promise<Array<database.Dictionary>>;

export function ListDictionaryItems(arg1:number):Promise<Array<database.DictionaryItem>>;

export function ListSqlTemplates():Promise<Array<services.TemplateListItem>>;

export function ListTabs():Promise<Array<database.Tab>>;

export function ListTemplates():Promise<Array<database.SQLTemplate>>;

export function LoadDictionaryCache():Promise<Record<number, Array<database.DictionaryItem>>>;

export function PreviewTemplate(arg1:string,arg2:Record<string, any>):Promise<string>;

export function QueryVariableOptions(arg1:number,arg2:string):Promise<Array<Record<string, any>>>;

export function RevealPassword(arg1:string):Promise<string>;

export function SaveConnection(arg1:database.DBConnection):Promise<number>;

export function SaveDictionary(arg1:database.Dictionary):Promise<number>;

export function SaveDictionaryItems(arg1:number,arg2:Array<database.DictionaryItem>):Promise<void>;

export function SaveSetting(arg1:string,arg2:string):Promise<void>;

export function SaveSqlTemplate(arg1:database.SQLTemplate):Promise<number>;

export function SaveTabs(arg1:Array<database.Tab>):Promise<Array<database.Tab>>;

export function SaveTemplate(arg1:database.SQLTemplate):Promise<number>;

export function TestConnection(arg1:database.DBConnection):Promise<void>;

export function ValidateScript(arg1:string):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowIsMaximised():Promise<boolean>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
