// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeforeClose(arg1) {
  return window['go']['app']['App']['BeforeClose'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['app']['App']['DeleteConnection'](arg1);
}

export function DeleteDictionary(arg1) {
  return window['go']['app']['App']['DeleteDictionary'](arg1);
}

export function DeleteSqlTemplate(arg1) {
  return window['go']['app']['App']['DeleteSqlTemplate'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['app']['App']['DeleteTemplate'](arg1);
}

export function ExecuteQuery(arg1) {
  return window['go']['app']['App']['ExecuteQuery'](arg1);
}

export function ExecuteTemplateQuery(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ExecuteTemplateQuery'](arg1, arg2, arg3, arg4, arg5);
}

export function ExtractTemplateVariables(arg1) {
  return window['go']['app']['App']['ExtractTemplateVariables'](arg1);
}

export function GetAllSettings() {
  return window['go']['app']['App']['GetAllSettings']();
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetConnection(arg1) {
  return window['go']['app']['App']['GetConnection'](arg1);
}

export function GetSqlTemplate(arg1) {
  return window['go']['app']['App']['GetSqlTemplate'](arg1);
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function ListConnections() {
  return window['go']['app']['App']['ListConnections']();
}

export function ListDictionaries() {
  return window['go']['app']['App']['ListDictionaries']();
}

export function ListDictionaryItems(arg1) {
  return window['go']['app']['App']['ListDictionaryItems'](arg1);
}

export function ListSqlTemplates() {
  return window['go']['app']['App']['ListSqlTemplates']();
}

export function ListTabs() {
  return window['go']['app']['App']['ListTabs']();
}

export function ListTemplates() {
  return window['go']['app']['App']['ListTemplates']();
}

export function LoadDictionaryCache() {
  return window['go']['app']['App']['LoadDictionaryCache']();
}

export function PreviewTemplate(arg1, arg2) {
  return window['go']['app']['App']['PreviewTemplate'](arg1, arg2);
}

export function QueryVariableOptions(arg1, arg2) {
  return window['go']['app']['App']['QueryVariableOptions'](arg1, arg2);
}

export function RevealPassword(arg1) {
  return window['go']['app']['App']['RevealPassword'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['app']['App']['SaveConnection'](arg1);
}

export function SaveDictionary(arg1) {
  return window['go']['app']['App']['SaveDictionary'](arg1);
}

export function SaveDictionaryItems(arg1, arg2) {
  return window['go']['app']['App']['SaveDictionaryItems'](arg1, arg2);
}

export function SaveSetting(arg1, arg2) {
  return window['go']['app']['App']['SaveSetting'](arg1, arg2);
}

export function SaveSqlTemplate(arg1) {
  return window['go']['app']['App']['SaveSqlTemplate'](arg1);
}

export function SaveTabs(arg1) {
  return window['go']['app']['App']['SaveTabs'](arg1);
}

export function SaveTemplate(arg1) {
  return window['go']['app']['App']['SaveTemplate'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['app']['App']['TestConnection'](arg1);
}

export function ValidateScript(arg1) {
  return window['go']['app']['App']['ValidateScript'](arg1);
}

export function WindowClose() {
  return window['go']['app']['App']['WindowClose']();
}

export function WindowIsMaximised() {
  return window['go']['app']['App']['WindowIsMaximised']();
}

export function WindowMinimise() {
  return window['go']['app']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['app']['App']['WindowToggleMaximise']();
}
