// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Snapshot 更新状态的完整快照：前端唯一的状态源。
 */
export class Snapshot {
    /**
     * Creates a new Snapshot instance.
     * @param {Partial<Snapshot>} [$$source = {}] - The source object to create the Snapshot.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * State 当前阶段，见上面的 State 常量
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("currentVersion" in $$source)) {
            /**
             * CurrentVersion 当前运行的版本
             * @member
             * @type {string}
             */
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            /**
             * LatestVersion 已发现的新版本（无则空）
             * @member
             * @type {string}
             */
            this["latestVersion"] = "";
        }
        if (!("notes" in $$source)) {
            /**
             * Notes 发版说明（GitHub Release 正文）
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }
        if (!("publishedAt" in $$source)) {
            /**
             * PublishedAt 发布时间（RFC3339，未知时为空）
             * @member
             * @type {string}
             */
            this["publishedAt"] = "";
        }
        if (!("assetName" in $$source)) {
            /**
             * AssetName 更新包文件名
             * @member
             * @type {string}
             */
            this["assetName"] = "";
        }
        if (!("assetSize" in $$source)) {
            /**
             * AssetSize 更新包字节数
             * @member
             * @type {number}
             */
            this["assetSize"] = 0;
        }
        if (!("available" in $$source)) {
            /**
             * Available 是否已发现可安装的新版本
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("progress" in $$source)) {
            /**
             * Progress 下载进度百分比；-1 表示总长未知
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }
        if (!("written" in $$source)) {
            /**
             * Written 已下载字节数
             * @member
             * @type {number}
             */
            this["written"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * Total 更新包总字节数（未知为 0）
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * Message 状态说明（不可用原因 / 已取消等）
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * Error 最近一次失败原因（无失败为空）
             * @member
             * @type {string}
             */
            this["error"] = "";
        }
        if (!("canCheck" in $$source)) {
            /**
             * CanCheck 现在可以发起检查
             * @member
             * @type {boolean}
             */
            this["canCheck"] = false;
        }
        if (!("canDownload" in $$source)) {
            /**
             * CanDownload 现在可以（或重试）下载
             * @member
             * @type {boolean}
             */
            this["canDownload"] = false;
        }
        if (!("canCancel" in $$source)) {
            /**
             * CanCancel 现在可以取消下载
             * @member
             * @type {boolean}
             */
            this["canCancel"] = false;
        }
        if (!("canRestart" in $$source)) {
            /**
             * CanRestart 现在可以重启生效
             * @member
             * @type {boolean}
             */
            this["canRestart"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Snapshot}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Snapshot(/** @type {Partial<Snapshot>} */($$parsedSource));
    }
}
