// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DBConnection 对应 db_connections 表，描述一个外部数据库连接。
 * Password 在数据库中为密文，对外返回时保持密文，由前端按需解密展示。
 */
export class DBConnection {
    /**
     * Creates a new DBConnection instance.
     * @param {Partial<DBConnection>} [$$source = {}] - The source object to create the DBConnection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("dbType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dbType"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("extra" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["extra"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DBConnection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DBConnection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DBConnection(/** @type {Partial<DBConnection>} */($$parsedSource));
    }
}

/**
 * Dictionary 对应 dictionaries 表。
 */
export class Dictionary {
    /**
     * Creates a new Dictionary instance.
     * @param {Partial<Dictionary>} [$$source = {}] - The source object to create the Dictionary.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Dictionary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Dictionary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Dictionary(/** @type {Partial<Dictionary>} */($$parsedSource));
    }
}

/**
 * DictionaryItem 对应 dictionary_items 表。
 */
export class DictionaryItem {
    /**
     * Creates a new DictionaryItem instance.
     * @param {Partial<DictionaryItem>} [$$source = {}] - The source object to create the DictionaryItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("dictionaryId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dictionaryId"] = 0;
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("meaning" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["meaning"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("sortOrder" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sortOrder"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DictionaryItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DictionaryItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DictionaryItem(/** @type {Partial<DictionaryItem>} */($$parsedSource));
    }
}

/**
 * SQLTemplate 对应 sql_templates 表。
 * Variables 与 FieldMappings 均为 JSON 字符串。
 */
export class SQLTemplate {
    /**
     * Creates a new SQLTemplate instance.
     * @param {Partial<SQLTemplate>} [$$source = {}] - The source object to create the SQLTemplate.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("connId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["connId"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("sqlText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sqlText"] = "";
        }
        if (!("variables" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["variables"] = "";
        }
        if (!("fieldMappings" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fieldMappings"] = "";
        }
        if (!("preScript" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["preScript"] = "";
        }
        if (!("postScript" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["postScript"] = "";
        }
        if (!("paginationEnabled" in $$source)) {
            /**
             * PaginationEnabled 是否对查询结果分页。
             * 开启后执行时会自动统计总数据量，并按 PageSize 切页。
             * @member
             * @type {boolean}
             */
            this["paginationEnabled"] = false;
        }
        if (!("pageSize" in $$source)) {
            /**
             * PageSize 每页条数，仅在 PaginationEnabled 为真时生效
             * @member
             * @type {number}
             */
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SQLTemplate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SQLTemplate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SQLTemplate(/** @type {Partial<SQLTemplate>} */($$parsedSource));
    }
}

/**
 * Setting 对应 app_settings 表。
 * Value 以字符串原样存储，由前端按 Type 解析（string/number/boolean/json/array）。
 */
export class Setting {
    /**
     * Creates a new Setting instance.
     * @param {Partial<Setting>} [$$source = {}] - The source object to create the Setting.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Setting instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Setting}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Setting(/** @type {Partial<Setting>} */($$parsedSource));
    }
}

/**
 * Tab 对应 tabs 表，描述一个工作台标签。
 * Payload 为各工具私有状态的 JSON 字符串，由前端序列化。
 */
export class Tab {
    /**
     * Creates a new Tab instance.
     * @param {Partial<Tab>} [$$source = {}] - The source object to create the Tab.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("sortOrder" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sortOrder"] = 0;
        }
        if (!("isActive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isActive"] = false;
        }
        if (!("isLocked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isLocked"] = false;
        }
        if (!("toolType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toolType"] = "";
        }
        if (!("payload" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["payload"] = "";
        }
        if (!("schemaVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["schemaVersion"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tab instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Tab}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tab(/** @type {Partial<Tab>} */($$parsedSource));
    }
}
