// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 是绑定到前端的根结构体
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "./internal/database/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "./internal/services/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "./internal/update/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as utils$0 from "./internal/utils/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Attach 注入 Wails 应用实例
 * @param {application$0.App | null} wailsApp
 * @returns {$CancellablePromise<void>}
 */
export function Attach(wailsApp) {
    return $Call.ByID(2676888505, wailsApp);
}

/**
 * AttachWindow 注入主窗口引用
 * @param {application$0.WebviewWindow | null} window
 * @returns {$CancellablePromise<void>}
 */
export function AttachWindow(window) {
    return $Call.ByID(1226334729, window);
}

/**
 * CancelUpdate 取消正在进行的下载（回到「有新版本可下载」状态）。
 * @returns {$CancellablePromise<void>}
 */
export function CancelUpdate() {
    return $Call.ByID(699082623);
}

/**
 * CheckUpdate 检查新版本。
 * 
 * 已有检查或下载在跑时直接返回（不打断当前流程）：前端继续读 UpdateSnapshot 即可。
 * @returns {$CancellablePromise<void>}
 */
export function CheckUpdate() {
    return $Call.ByID(264084285);
}

/**
 * DeleteConnection 删除连接配置。
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteConnection(id) {
    return $Call.ByID(1000710359, id);
}

/**
 * DeleteDictionary 删除词典。
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteDictionary(id) {
    return $Call.ByID(975524167, id);
}

/**
 * DeleteSqlTemplate 删除模板。
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSqlTemplate(id) {
    return $Call.ByID(3169122111, id);
}

/**
 * DeleteTemplate 兼容旧接口。
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTemplate(id) {
    return $Call.ByID(3133623549, id);
}

/**
 * DownloadUpdate 下载并安装已发现的新版本；取消走 CancelUpdate。
 * @returns {$CancellablePromise<void>}
 */
export function DownloadUpdate() {
    return $Call.ByID(3747271165);
}

/**
 * ExecuteQuery 执行查询：前置脚本 → 模板渲染 → SQL 执行 → 后置脚本。
 * @param {services$0.ExecuteRequest} req
 * @returns {$CancellablePromise<services$0.QueryResult | null>}
 */
export function ExecuteQuery(req) {
    return $Call.ByID(722935905, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ExecuteStatement 执行用户输入的任意 SQL
 * @param {services$0.ExecutorRequest} req
 * @returns {$CancellablePromise<services$0.ExecutorResult | null>}
 */
export function ExecuteStatement(req) {
    return $Call.ByID(1693566536, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ExecuteTemplateQuery 按模板执行查询
 * @param {services$0.TemplateExecuteRequest} req
 * @returns {$CancellablePromise<services$0.QueryResult | null>}
 */
export function ExecuteTemplateQuery(req) {
    return $Call.ByID(2760232183, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ExtractTemplateVariables 解析 SQL 模板中的变量名。
 * @param {string} sqlText
 * @returns {$CancellablePromise<string[]>}
 */
export function ExtractTemplateVariables(sqlText) {
    return $Call.ByID(347742172, sqlText).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * FetchCreateTableSQL 返回数据库自己的建表语句（拿不到时返回空串，由前端生成）。
 * @param {number} connID
 * @param {string} database
 * @param {string} table
 * @returns {$CancellablePromise<string>}
 */
export function FetchCreateTableSQL(connID, database, table) {
    return $Call.ByID(3199721432, connID, database, table);
}

/**
 * GetAllSettings 返回全部应用配置
 * @returns {$CancellablePromise<database$0.Setting[]>}
 */
export function GetAllSettings() {
    return $Call.ByID(2335488078).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetAppInfo 返回应用与运行环境信息。
 * @returns {$CancellablePromise<$models.AppInfo>}
 */
export function GetAppInfo() {
    return $Call.ByID(2996357887).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetAppStartupState 应用启动状态（degraded 时前端展示原因与重试入口）。
 * @returns {$CancellablePromise<$models.AppStartupState>}
 */
export function GetAppStartupState() {
    return $Call.ByID(2620907841).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetConnection 返回单个连接配置。
 * @param {number} id
 * @returns {$CancellablePromise<database$0.DBConnection | null>}
 */
export function GetConnection(id) {
    return $Call.ByID(1115056712, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetSqlTemplate 按 ID 返回完整模板。
 * @param {number} id
 * @returns {$CancellablePromise<database$0.SQLTemplate | null>}
 */
export function GetSqlTemplate(id) {
    return $Call.ByID(372381126, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * Greet 返回一句问候语
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(1568700365, name);
}

/**
 * ListConnections 返回全部数据库连接配置（密码为密文）
 * @returns {$CancellablePromise<database$0.DBConnection[]>}
 */
export function ListConnections() {
    return $Call.ByID(1603679501).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * ListDatabases 返回连接可见的所有数据库
 * @param {number} connID
 * @returns {$CancellablePromise<services$0.DatabaseInfo[]>}
 */
export function ListDatabases(connID) {
    return $Call.ByID(1767885062, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * ListDictionaries 返回全部词典。
 * @returns {$CancellablePromise<database$0.Dictionary[]>}
 */
export function ListDictionaries() {
    return $Call.ByID(4063091332).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * ListDictionaryItems 返回指定词典的全部项。
 * @param {number} dictionaryID
 * @returns {$CancellablePromise<database$0.DictionaryItem[]>}
 */
export function ListDictionaryItems(dictionaryID) {
    return $Call.ByID(3553481380, dictionaryID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * ListForeignKeys 返回指定表的外键约束
 * @param {number} connID
 * @param {string} database
 * @param {string} table
 * @returns {$CancellablePromise<services$0.ForeignKey[]>}
 */
export function ListForeignKeys(connID, database, table) {
    return $Call.ByID(1478162384, connID, database, table).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * ListSqlTemplates 返回模板列表（含截断的 SQL 预览）
 * @returns {$CancellablePromise<services$0.TemplateListItem[]>}
 */
export function ListSqlTemplates() {
    return $Call.ByID(3723117187).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * ListSystemFonts 返回本机已安装的字体族名称列表
 * @returns {$CancellablePromise<string[]>}
 */
export function ListSystemFonts() {
    return $Call.ByID(1215069897).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListTableColumns 返回指定表的字段信息（名称 / 类型 / 注释）。
 * @param {number} connID
 * @param {string} database
 * @param {string} table
 * @returns {$CancellablePromise<services$0.ExecutorColumn[]>}
 */
export function ListTableColumns(connID, database, table) {
    return $Call.ByID(832508427, connID, database, table).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * ListTables 返回指定库下的表与视图名
 * @param {number} connID
 * @param {string} database
 * @returns {$CancellablePromise<string[]>}
 */
export function ListTables(connID, database) {
    return $Call.ByID(2064401305, connID, database).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListTabs 返回全部工作台 Tab。
 * @returns {$CancellablePromise<database$0.Tab[]>}
 */
export function ListTabs() {
    return $Call.ByID(4125257976).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * ListTemplates 返回全部模板（含完整字段，兼容旧接口）
 * @returns {$CancellablePromise<database$0.SQLTemplate[]>}
 */
export function ListTemplates() {
    return $Call.ByID(1375775183).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * LoadDictionaryCache 一次性加载全部词典与词典项，供前端本地翻译使用
 * @returns {$CancellablePromise<{ [_ in `${number}`]?: database$0.DictionaryItem[] }>}
 */
export function LoadDictionaryCache() {
    return $Call.ByID(212418086).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

/**
 * NotifyBeforeQuit 通知前端保存当前状态
 * @returns {$CancellablePromise<void>}
 */
export function NotifyBeforeQuit() {
    return $Call.ByID(1771222557);
}

/**
 * PreviewTemplate 渲染模板，返回最终 SQL。
 * @param {string} sqlText
 * @param {{ [_ in string]?: any }} variables
 * @returns {$CancellablePromise<string>}
 */
export function PreviewTemplate(sqlText, variables) {
    return $Call.ByID(3030310906, sqlText, variables);
}

/**
 * QueryVariableOptions 执行 SQL 取变量的动态选项
 * @param {number} connID
 * @param {string} query
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function QueryVariableOptions(connID, query) {
    return $Call.ByID(454558478, connID, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType31($result);
    }));
}

/**
 * RenderExportTemplate 按导出模板渲染选中的结果行，返回逐行文本
 * @param {string} tplText
 * @param {{ [_ in string]?: any }[]} rows
 * @returns {$CancellablePromise<string[]>}
 */
export function RenderExportTemplate(tplText, rows) {
    return $Call.ByID(3743317892, tplText, rows).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * RestartToApplyUpdate 重启应用以应用已下载的更新（仅「已就绪」时可用）。
 * @returns {$CancellablePromise<void>}
 */
export function RestartToApplyUpdate() {
    return $Call.ByID(486819579);
}

/**
 * RetryInit 重新执行初始化。
 * 
 * 用于数据库损坏、目录权限异常等情况下的自救：成功后本地数据功能恢复，
 * 失败则把新的原因回给前端。已经初始化成功时直接返回当前状态（不重复打开数据库）。
 * @returns {$CancellablePromise<$models.AppStartupState>}
 */
export function RetryInit() {
    return $Call.ByID(1405400900).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * RevealPassword 解密并返回明文密码
 * @param {string} encrypted
 * @returns {$CancellablePromise<string>}
 */
export function RevealPassword(encrypted) {
    return $Call.ByID(2751539972, encrypted);
}

/**
 * SaveConnection 保存连接配置，密码自动加密。
 * @param {database$0.DBConnection} conn
 * @returns {$CancellablePromise<number>}
 */
export function SaveConnection(conn) {
    return $Call.ByID(962426477, conn);
}

/**
 * SaveDictionary 新增或更新词典。
 * @param {database$0.Dictionary} dict
 * @returns {$CancellablePromise<number>}
 */
export function SaveDictionary(dict) {
    return $Call.ByID(2240710481, dict);
}

/**
 * SaveDictionaryItems 全量保存某词典的项目。
 * @param {number} dictionaryID
 * @param {database$0.DictionaryItem[]} items
 * @returns {$CancellablePromise<void>}
 */
export function SaveDictionaryItems(dictionaryID, items) {
    return $Call.ByID(1865529947, dictionaryID, items);
}

/**
 * SaveSetting 写入单个配置项。
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SaveSetting(key, value) {
    return $Call.ByID(2667885095, key, value);
}

/**
 * SaveSqlTemplate 新增或更新模板（id 为 0 时插入）
 * @param {database$0.SQLTemplate} tpl
 * @returns {$CancellablePromise<number>}
 */
export function SaveSqlTemplate(tpl) {
    return $Call.ByID(3223063081, tpl);
}

/**
 * SaveTabs 全量保存 Tab 列表，返回带真实 ID 的列表
 * @param {database$0.Tab[]} tabs
 * @returns {$CancellablePromise<database$0.Tab[]>}
 */
export function SaveTabs(tabs) {
    return $Call.ByID(2851052225, tabs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * SaveTemplate 兼容旧接口
 * @param {database$0.SQLTemplate} tpl
 * @returns {$CancellablePromise<number>}
 */
export function SaveTemplate(tpl) {
    return $Call.ByID(1828473719, tpl);
}

/**
 * TestConnection 测试连接是否可用。
 * @param {database$0.DBConnection} conn
 * @returns {$CancellablePromise<void>}
 */
export function TestConnection(conn) {
    return $Call.ByID(2260153928, conn);
}

/**
 * UpdateSnapshot 当前更新状态的完整快照：前端唯一的状态源。
 * 
 * 更新能力不可用时也返回快照（state 为 unconfigured，message 说明原因），
 * 前端不需要为「不可用」单独准备一套展示逻辑。
 * @returns {$CancellablePromise<update$0.Snapshot>}
 */
export function UpdateSnapshot() {
    return $Call.ByID(4184629245).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * ValidateScript 校验前置/后置脚本语法。
 * @param {string} source
 * @returns {$CancellablePromise<void>}
 */
export function ValidateScript(source) {
    return $Call.ByID(1351361145, source);
}

/**
 * ValidateTemplate 校验模板语法，返回错误位置供编辑器标注
 * @param {string} sqlText
 * @returns {$CancellablePromise<utils$0.TemplateCheck>}
 */
export function ValidateTemplate(sqlText) {
    return $Call.ByID(3453963828, sqlText).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType33($result);
    }));
}

/**
 * WindowClose 关闭窗口并退出应用。
 * @returns {$CancellablePromise<void>}
 */
export function WindowClose() {
    return $Call.ByID(852980156);
}

/**
 * WindowIsMaximised 窗口是否最大化
 * @returns {$CancellablePromise<boolean>}
 */
export function WindowIsMaximised() {
    return $Call.ByID(3876954769);
}

/**
 * WindowMinimise 最小化窗口
 * @returns {$CancellablePromise<void>}
 */
export function WindowMinimise() {
    return $Call.ByID(2950607653);
}

/**
 * WindowToggleMaximise 切换最大化与还原
 * @returns {$CancellablePromise<void>}
 */
export function WindowToggleMaximise() {
    return $Call.ByID(492636603);
}

// Private type creation functions
const $$createType0 = services$0.QueryResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = services$0.ExecutorResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = database$0.Setting.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.AppInfo.createFrom;
const $$createType8 = $models.AppStartupState.createFrom;
const $$createType9 = database$0.DBConnection.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = database$0.SQLTemplate.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $Create.Array($$createType9);
const $$createType14 = services$0.DatabaseInfo.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = database$0.Dictionary.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = database$0.DictionaryItem.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = services$0.ForeignKey.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = services$0.TemplateListItem.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = services$0.ExecutorColumn.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = database$0.Tab.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = $Create.Array($$createType11);
const $$createType29 = $Create.Map($Create.Any, $$createType19);
const $$createType30 = $Create.Map($Create.Any, $Create.Any);
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = update$0.Snapshot.createFrom;
const $$createType33 = utils$0.TemplateCheck.createFrom;
