// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 是绑定到前端的根结构体，所有导出方法都会生成前端可调用的绑定。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "./internal/database/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "./internal/services/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Attach 注入 Wails 应用实例。
 * 必须在 application.New 之后、app.Run 之前调用。
 * @param {application$0.App | null} wailsApp
 * @returns {$CancellablePromise<void>}
 */
export function Attach(wailsApp) {
    return $Call.ByID(2676888505, wailsApp);
}

/**
 * DeleteConnection 删除连接配置。
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteConnection(id) {
    return $Call.ByID(1000710359, id);
}

/**
 * DeleteDictionary 删除词典。
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteDictionary(id) {
    return $Call.ByID(975524167, id);
}

/**
 * DeleteSqlTemplate 删除模板。
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSqlTemplate(id) {
    return $Call.ByID(3169122111, id);
}

/**
 * DeleteTemplate 兼容旧接口。
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTemplate(id) {
    return $Call.ByID(3133623549, id);
}

/**
 * ExecuteQuery 执行查询：前置脚本 → 模板渲染 → SQL 执行 → 后置脚本。
 * @param {services$0.ExecuteRequest} req
 * @returns {$CancellablePromise<services$0.QueryResult | null>}
 */
export function ExecuteQuery(req) {
    return $Call.ByID(722935905, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ExecuteTemplateQuery 按模板执行查询。
 * 
 * 完整链路：取模板 → 补全变量 → 前置脚本 → 渲染 SQL → 执行 → 后置脚本。
 * 模板更新后，引用它的 Tab 无需同步即可在下次执行时生效。
 * 
 * req 中的 Page / PageSize 仅在模板开启分页时生效，未开启时后端会自动忽略。
 * Total 与 CountTotal 用于翻页时复用总数：翻页传上次返回的 total 且 CountTotal=false。
 * @param {services$0.TemplateExecuteRequest} req
 * @returns {$CancellablePromise<services$0.QueryResult | null>}
 */
export function ExecuteTemplateQuery(req) {
    return $Call.ByID(2760232183, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ExtractTemplateVariables 解析 SQL 模板中的变量名。
 * @param {string} sqlText
 * @returns {$CancellablePromise<string[]>}
 */
export function ExtractTemplateVariables(sqlText) {
    return $Call.ByID(347742172, sqlText).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetAllSettings 返回全部应用配置。
 * 首次调用会写入默认值，保证前端总能拿到完整配置。
 * @returns {$CancellablePromise<database$0.Setting[]>}
 */
export function GetAllSettings() {
    return $Call.ByID(2335488078).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetAppInfo 返回当前应用与运行环境信息。
 * @returns {$CancellablePromise<$models.AppInfo>}
 */
export function GetAppInfo() {
    return $Call.ByID(2996357887).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetConnection 返回单个连接配置。
 * @param {number} id
 * @returns {$CancellablePromise<database$0.DBConnection | null>}
 */
export function GetConnection(id) {
    return $Call.ByID(1115056712, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetSqlTemplate 按 ID 返回完整模板。
 * @param {number} id
 * @returns {$CancellablePromise<database$0.SQLTemplate | null>}
 */
export function GetSqlTemplate(id) {
    return $Call.ByID(372381126, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * Greet 返回一句问候语，用于演示前后端调用链路。
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(1568700365, name);
}

/**
 * ListConnections 返回全部数据库连接配置。
 * 密码字段为密文，前端展示时用掩码，仅在用户主动查看时调用 RevealPassword。
 * @returns {$CancellablePromise<database$0.DBConnection[]>}
 */
export function ListConnections() {
    return $Call.ByID(1603679501).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * ListDictionaries 返回全部词典。
 * @returns {$CancellablePromise<database$0.Dictionary[]>}
 */
export function ListDictionaries() {
    return $Call.ByID(4063091332).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * ListDictionaryItems 返回指定词典的全部项。
 * @param {number} dictionaryID
 * @returns {$CancellablePromise<database$0.DictionaryItem[]>}
 */
export function ListDictionaryItems(dictionaryID) {
    return $Call.ByID(3553481380, dictionaryID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * ListSqlTemplates 返回模板列表（含截断的 SQL 预览）。
 * 列表场景无需完整 SQL，截断可显著减少 IPC 传输量。
 * @returns {$CancellablePromise<services$0.TemplateListItem[]>}
 */
export function ListSqlTemplates() {
    return $Call.ByID(3723117187).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * ListSystemFonts 返回本机已安装的字体族名称列表。
 * 
 * 供设置面板的字体下拉使用（前端拼成字体栈）。
 * 列表在单次运行内缓存，重复调用不会重复读取注册表。
 * @returns {$CancellablePromise<string[]>}
 */
export function ListSystemFonts() {
    return $Call.ByID(1215069897).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListTabs 返回全部工作台 Tab。
 * @returns {$CancellablePromise<database$0.Tab[]>}
 */
export function ListTabs() {
    return $Call.ByID(4125257976).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * ListTemplates 返回全部模板（含完整字段）。
 * 保留该方法以兼容已有调用。
 * @returns {$CancellablePromise<database$0.SQLTemplate[]>}
 */
export function ListTemplates() {
    return $Call.ByID(1375775183).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * LoadDictionaryCache 一次性加载全部词典与词典项，供前端本地翻译使用。
 * 词典数据量小且读多写少，一次拉取可避免每格查询带来的延迟。
 * @returns {$CancellablePromise<{ [_ in `${number}`]?: database$0.DictionaryItem[] }>}
 */
export function LoadDictionaryCache() {
    return $Call.ByID(212418086).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * NotifyBeforeQuit 通知前端立即保存当前状态。
 * 
 * 前端配合方式：监听 "app:before-quit" 事件并调用 SaveTabs。
 * 这里只做通知不做阻塞等待——SQLite 写入是本地操作，通常毫秒级完成，
 * 而阻塞等待一旦异常会导致窗口无法关闭，体验更差。
 * @returns {$CancellablePromise<void>}
 */
export function NotifyBeforeQuit() {
    return $Call.ByID(1771222557);
}

/**
 * PreviewTemplate 渲染模板，返回最终 SQL。
 * @param {string} sqlText
 * @param {{ [_ in string]?: any }} variables
 * @returns {$CancellablePromise<string>}
 */
export function PreviewTemplate(sqlText, variables) {
    return $Call.ByID(3030310906, sqlText, variables);
}

/**
 * QueryVariableOptions 执行 SQL 以获取变量的动态选项。
 * @param {number} connID
 * @param {string} query
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function QueryVariableOptions(connID, query) {
    return $Call.ByID(454558478, connID, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * RevealPassword 解密并返回明文密码。
 * 仅在用户明确点击「显示密码」时调用，避免明文在任何列表接口中泄露。
 * @param {string} encrypted
 * @returns {$CancellablePromise<string>}
 */
export function RevealPassword(encrypted) {
    return $Call.ByID(2751539972, encrypted);
}

/**
 * SaveConnection 保存连接配置，密码自动加密。
 * @param {database$0.DBConnection} conn
 * @returns {$CancellablePromise<number>}
 */
export function SaveConnection(conn) {
    return $Call.ByID(962426477, conn);
}

/**
 * SaveDictionary 新增或更新词典。
 * @param {database$0.Dictionary} dict
 * @returns {$CancellablePromise<number>}
 */
export function SaveDictionary(dict) {
    return $Call.ByID(2240710481, dict);
}

/**
 * SaveDictionaryItems 全量保存某词典的项目。
 * @param {number} dictionaryID
 * @param {database$0.DictionaryItem[]} items
 * @returns {$CancellablePromise<void>}
 */
export function SaveDictionaryItems(dictionaryID, items) {
    return $Call.ByID(1865529947, dictionaryID, items);
}

/**
 * SaveSetting 写入单个配置项。
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SaveSetting(key, value) {
    return $Call.ByID(2667885095, key, value);
}

/**
 * SaveSqlTemplate 新增或更新模板。id 为 0 时插入，否则更新。
 * @param {database$0.SQLTemplate} tpl
 * @returns {$CancellablePromise<number>}
 */
export function SaveSqlTemplate(tpl) {
    return $Call.ByID(3223063081, tpl);
}

/**
 * SaveTabs 全量保存 Tab 列表，返回写入后带真实 ID 的列表。
 * 
 * 前端在 state 变化后防抖 1s 调用；退出时再同步调用一次兜底。
 * 返回回填 ID 的列表是必要的：前端新建标签使用负数占位 ID，
 * 保存后需要用数据库分配的 ID 替换，否则下次保存时关联关系会错乱。
 * @param {database$0.Tab[]} tabs
 * @returns {$CancellablePromise<database$0.Tab[]>}
 */
export function SaveTabs(tabs) {
    return $Call.ByID(2851052225, tabs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * SaveTemplate 兼容旧接口，等价于 SaveSqlTemplate。
 * @param {database$0.SQLTemplate} tpl
 * @returns {$CancellablePromise<number>}
 */
export function SaveTemplate(tpl) {
    return $Call.ByID(1828473719, tpl);
}

/**
 * TestConnection 测试连接是否可用。
 * @param {database$0.DBConnection} conn
 * @returns {$CancellablePromise<void>}
 */
export function TestConnection(conn) {
    return $Call.ByID(2260153928, conn);
}

/**
 * ValidateScript 校验前置/后置脚本语法。
 * @param {string} source
 * @returns {$CancellablePromise<void>}
 */
export function ValidateScript(source) {
    return $Call.ByID(1351361145, source);
}

/**
 * WindowClose 关闭窗口并退出应用。
 * @returns {$CancellablePromise<void>}
 */
export function WindowClose() {
    return $Call.ByID(852980156);
}

/**
 * WindowIsMaximised 返回窗口当前是否处于最大化状态。
 * @returns {$CancellablePromise<boolean>}
 */
export function WindowIsMaximised() {
    return $Call.ByID(3876954769);
}

/**
 * WindowMinimise 最小化窗口。
 * @returns {$CancellablePromise<void>}
 */
export function WindowMinimise() {
    return $Call.ByID(2950607653);
}

/**
 * WindowToggleMaximise 在最大化与还原之间切换。
 * @returns {$CancellablePromise<void>}
 */
export function WindowToggleMaximise() {
    return $Call.ByID(492636603);
}

// Private type creation functions
const $$createType0 = services$0.QueryResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = database$0.Setting.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.AppInfo.createFrom;
const $$createType6 = database$0.DBConnection.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = database$0.SQLTemplate.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType6);
const $$createType11 = database$0.Dictionary.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = database$0.DictionaryItem.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = services$0.TemplateListItem.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = database$0.Tab.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $Create.Array($$createType8);
const $$createType20 = $Create.Map($Create.Any, $$createType14);
const $$createType21 = $Create.Map($Create.Any, $Create.Any);
const $$createType22 = $Create.Array($$createType21);
