// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 是绑定到前端的根结构体，所有导出方法都会生成前端可调用的绑定。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "./internal/database/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "./internal/services/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Attach 注入 Wails 应用实例。
 * 必须在 application.New 之后、app.Run 之前调用。
 * @param {application$0.App | null} wailsApp
 * @returns {$CancellablePromise<void>}
 */
export function Attach(wailsApp) {
    return $Call.ByID(2676888505, wailsApp);
}

/**
 * AttachWindow 注入主窗口引用，供窗口背景材质等需要原生句柄的操作使用。
 * 必须在 app.Run 之前调用（与 Attach 一起）。
 * @param {application$0.WebviewWindow | null} window
 * @returns {$CancellablePromise<void>}
 */
export function AttachWindow(window) {
    return $Call.ByID(1226334729, window);
}

/**
 * DeleteConnection 删除连接配置。
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteConnection(id) {
    return $Call.ByID(1000710359, id);
}

/**
 * DeleteDictionary 删除词典。
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteDictionary(id) {
    return $Call.ByID(975524167, id);
}

/**
 * DeleteSqlTemplate 删除模板。
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSqlTemplate(id) {
    return $Call.ByID(3169122111, id);
}

/**
 * DeleteTemplate 兼容旧接口。
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTemplate(id) {
    return $Call.ByID(3133623549, id);
}

/**
 * ExecuteQuery 执行查询：前置脚本 → 模板渲染 → SQL 执行 → 后置脚本。
 * @param {services$0.ExecuteRequest} req
 * @returns {$CancellablePromise<services$0.QueryResult | null>}
 */
export function ExecuteQuery(req) {
    return $Call.ByID(722935905, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ExecuteStatement 执行用户输入的任意 SQL。
 * 
 * ctx 由 Wails 注入：前端对返回的 CancellablePromise 调用 cancel 时，
 * 该 ctx 会被取消，数据库端正在执行的语句随之终止。
 * @param {services$0.ExecutorRequest} req
 * @returns {$CancellablePromise<services$0.ExecutorResult | null>}
 */
export function ExecuteStatement(req) {
    return $Call.ByID(1693566536, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ExecuteTemplateQuery 按模板执行查询。
 * 
 * 完整链路：取模板 → 补全变量 → 前置脚本 → 渲染 SQL → 执行 → 后置脚本。
 * 模板更新后，引用它的 Tab 无需同步即可在下次执行时生效。
 * 
 * req 中的 Page / PageSize 仅在模板开启分页时生效，未开启时后端会自动忽略。
 * Total 与 CountTotal 用于翻页时复用总数：翻页传上次返回的 total 且 CountTotal=false。
 * @param {services$0.TemplateExecuteRequest} req
 * @returns {$CancellablePromise<services$0.QueryResult | null>}
 */
export function ExecuteTemplateQuery(req) {
    return $Call.ByID(2760232183, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ExtractTemplateVariables 解析 SQL 模板中的变量名。
 * @param {string} sqlText
 * @returns {$CancellablePromise<string[]>}
 */
export function ExtractTemplateVariables(sqlText) {
    return $Call.ByID(347742172, sqlText).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetAllSettings 返回全部应用配置。
 * 首次调用会写入默认值，保证前端总能拿到完整配置。
 * @returns {$CancellablePromise<database$0.Setting[]>}
 */
export function GetAllSettings() {
    return $Call.ByID(2335488078).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetAppInfo 返回当前应用与运行环境信息。
 * @returns {$CancellablePromise<$models.AppInfo>}
 */
export function GetAppInfo() {
    return $Call.ByID(2996357887).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetConnection 返回单个连接配置。
 * @param {number} id
 * @returns {$CancellablePromise<database$0.DBConnection | null>}
 */
export function GetConnection(id) {
    return $Call.ByID(1115056712, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetSqlTemplate 按 ID 返回完整模板。
 * @param {number} id
 * @returns {$CancellablePromise<database$0.SQLTemplate | null>}
 */
export function GetSqlTemplate(id) {
    return $Call.ByID(372381126, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetSystemMetrics 返回一次实时系统与应用资源采样（首页监控卡片轮询用）。
 * 
 * 说明：
 *   - 不访问数据库，因此不做 a.ready() 校验；
 *   - 采样内含 200ms 的 CPU 统计窗口，前端按 1~2 秒轮询即可，不必更密。
 * @returns {$CancellablePromise<services$0.SystemMetrics>}
 */
export function GetSystemMetrics() {
    return $Call.ByID(4270215138).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * Greet 返回一句问候语，用于演示前后端调用链路。
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(1568700365, name);
}

/**
 * ListConnections 返回全部数据库连接配置。
 * 密码字段为密文，前端展示时用掩码，仅在用户主动查看时调用 RevealPassword。
 * @returns {$CancellablePromise<database$0.DBConnection[]>}
 */
export function ListConnections() {
    return $Call.ByID(1603679501).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * ListDatabases 返回连接可见的所有数据库（库选择下拉）。
 * @param {number} connID
 * @returns {$CancellablePromise<string[]>}
 */
export function ListDatabases(connID) {
    return $Call.ByID(1767885062, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListDictionaries 返回全部词典。
 * @returns {$CancellablePromise<database$0.Dictionary[]>}
 */
export function ListDictionaries() {
    return $Call.ByID(4063091332).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * ListDictionaryItems 返回指定词典的全部项。
 * @param {number} dictionaryID
 * @returns {$CancellablePromise<database$0.DictionaryItem[]>}
 */
export function ListDictionaryItems(dictionaryID) {
    return $Call.ByID(3553481380, dictionaryID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * ListSqlTemplates 返回模板列表（含截断的 SQL 预览）。
 * 列表场景无需完整 SQL，截断可显著减少 IPC 传输量。
 * @returns {$CancellablePromise<services$0.TemplateListItem[]>}
 */
export function ListSqlTemplates() {
    return $Call.ByID(3723117187).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * ListSystemFonts 返回本机已安装的字体族名称列表。
 * 
 * 供设置面板的字体下拉使用（前端拼成字体栈）。
 * 列表在单次运行内缓存，重复调用不会重复读取注册表。
 * @returns {$CancellablePromise<string[]>}
 */
export function ListSystemFonts() {
    return $Call.ByID(1215069897).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListTableColumns 返回指定表的字段信息（名称 / 类型 / 注释）。
 * @param {number} connID
 * @param {string} database
 * @param {string} table
 * @returns {$CancellablePromise<services$0.ExecutorColumn[]>}
 */
export function ListTableColumns(connID, database, table) {
    return $Call.ByID(832508427, connID, database, table).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * ListTables 返回指定库下的表与视图名（智能补全与元数据展示）。
 * @param {number} connID
 * @param {string} database
 * @returns {$CancellablePromise<string[]>}
 */
export function ListTables(connID, database) {
    return $Call.ByID(2064401305, connID, database).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListTabs 返回全部工作台 Tab。
 * @returns {$CancellablePromise<database$0.Tab[]>}
 */
export function ListTabs() {
    return $Call.ByID(4125257976).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * ListTemplates 返回全部模板（含完整字段）。
 * 保留该方法以兼容已有调用。
 * @returns {$CancellablePromise<database$0.SQLTemplate[]>}
 */
export function ListTemplates() {
    return $Call.ByID(1375775183).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * LoadDictionaryCache 一次性加载全部词典与词典项，供前端本地翻译使用。
 * 词典数据量小且读多写少，一次拉取可避免每格查询带来的延迟。
 * @returns {$CancellablePromise<{ [_ in `${number}`]?: database$0.DictionaryItem[] }>}
 */
export function LoadDictionaryCache() {
    return $Call.ByID(212418086).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * NotifyBeforeQuit 通知前端立即保存当前状态。
 * 
 * 前端配合方式：监听 "app:before-quit" 事件并调用 SaveTabs。
 * 这里只做通知不做阻塞等待——SQLite 写入是本地操作，通常毫秒级完成，
 * 而阻塞等待一旦异常会导致窗口无法关闭，体验更差。
 * @returns {$CancellablePromise<void>}
 */
export function NotifyBeforeQuit() {
    return $Call.ByID(1771222557);
}

/**
 * PreviewTemplate 渲染模板，返回最终 SQL。
 * @param {string} sqlText
 * @param {{ [_ in string]?: any }} variables
 * @returns {$CancellablePromise<string>}
 */
export function PreviewTemplate(sqlText, variables) {
    return $Call.ByID(3030310906, sqlText, variables);
}

/**
 * QueryVariableOptions 执行 SQL 以获取变量的动态选项。
 * @param {number} connID
 * @param {string} query
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function QueryVariableOptions(connID, query) {
    return $Call.ByID(454558478, connID, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * RevealPassword 解密并返回明文密码。
 * 仅在用户明确点击「显示密码」时调用，避免明文在任何列表接口中泄露。
 * @param {string} encrypted
 * @returns {$CancellablePromise<string>}
 */
export function RevealPassword(encrypted) {
    return $Call.ByID(2751539972, encrypted);
}

/**
 * SaveConnection 保存连接配置，密码自动加密。
 * @param {database$0.DBConnection} conn
 * @returns {$CancellablePromise<number>}
 */
export function SaveConnection(conn) {
    return $Call.ByID(962426477, conn);
}

/**
 * SaveDictionary 新增或更新词典。
 * @param {database$0.Dictionary} dict
 * @returns {$CancellablePromise<number>}
 */
export function SaveDictionary(dict) {
    return $Call.ByID(2240710481, dict);
}

/**
 * SaveDictionaryItems 全量保存某词典的项目。
 * @param {number} dictionaryID
 * @param {database$0.DictionaryItem[]} items
 * @returns {$CancellablePromise<void>}
 */
export function SaveDictionaryItems(dictionaryID, items) {
    return $Call.ByID(1865529947, dictionaryID, items);
}

/**
 * SaveSetting 写入单个配置项。
 * 
 * 「窗口毛玻璃」开关要立刻作用到原生窗口（DWM 背景材质），
 * 因此在写库成功后同步应用一次。
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SaveSetting(key, value) {
    return $Call.ByID(2667885095, key, value);
}

/**
 * SaveSqlTemplate 新增或更新模板。id 为 0 时插入，否则更新。
 * @param {database$0.SQLTemplate} tpl
 * @returns {$CancellablePromise<number>}
 */
export function SaveSqlTemplate(tpl) {
    return $Call.ByID(3223063081, tpl);
}

/**
 * SaveTabs 全量保存 Tab 列表，返回写入后带真实 ID 的列表。
 * 
 * 前端在 state 变化后防抖 1s 调用；退出时再同步调用一次兜底。
 * 返回回填 ID 的列表是必要的：前端新建标签使用负数占位 ID，
 * 保存后需要用数据库分配的 ID 替换，否则下次保存时关联关系会错乱。
 * @param {database$0.Tab[]} tabs
 * @returns {$CancellablePromise<database$0.Tab[]>}
 */
export function SaveTabs(tabs) {
    return $Call.ByID(2851052225, tabs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * SaveTemplate 兼容旧接口，等价于 SaveSqlTemplate。
 * @param {database$0.SQLTemplate} tpl
 * @returns {$CancellablePromise<number>}
 */
export function SaveTemplate(tpl) {
    return $Call.ByID(1828473719, tpl);
}

/**
 * TestConnection 测试连接是否可用。
 * @param {database$0.DBConnection} conn
 * @returns {$CancellablePromise<void>}
 */
export function TestConnection(conn) {
    return $Call.ByID(2260153928, conn);
}

/**
 * ValidateScript 校验前置/后置脚本语法。
 * @param {string} source
 * @returns {$CancellablePromise<void>}
 */
export function ValidateScript(source) {
    return $Call.ByID(1351361145, source);
}

/**
 * WindowClose 关闭窗口并退出应用。
 * @returns {$CancellablePromise<void>}
 */
export function WindowClose() {
    return $Call.ByID(852980156);
}

/**
 * WindowIsMaximised 返回窗口当前是否处于最大化状态。
 * @returns {$CancellablePromise<boolean>}
 */
export function WindowIsMaximised() {
    return $Call.ByID(3876954769);
}

/**
 * WindowMinimise 最小化窗口。
 * @returns {$CancellablePromise<void>}
 */
export function WindowMinimise() {
    return $Call.ByID(2950607653);
}

/**
 * WindowToggleMaximise 在最大化与还原之间切换。
 * @returns {$CancellablePromise<void>}
 */
export function WindowToggleMaximise() {
    return $Call.ByID(492636603);
}

// Private type creation functions
const $$createType0 = services$0.QueryResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = services$0.ExecutorResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = database$0.Setting.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.AppInfo.createFrom;
const $$createType8 = database$0.DBConnection.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = database$0.SQLTemplate.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = services$0.SystemMetrics.createFrom;
const $$createType13 = $Create.Array($$createType8);
const $$createType14 = database$0.Dictionary.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = database$0.DictionaryItem.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = services$0.TemplateListItem.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = services$0.ExecutorColumn.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = database$0.Tab.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = $Create.Array($$createType10);
const $$createType25 = $Create.Map($Create.Any, $$createType17);
const $$createType26 = $Create.Map($Create.Any, $Create.Any);
const $$createType27 = $Create.Array($$createType26);
