// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppInfo 描述应用及运行环境的基本信息。
 */
export class AppInfo {
    /**
     * Creates a new AppInfo instance.
     * @param {Partial<AppInfo>} [$$source = {}] - The source object to create the AppInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("goVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["goVersion"] = "";
        }
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platform"] = "";
        }
        if (!("arch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppInfo(/** @type {Partial<AppInfo>} */($$parsedSource));
    }
}
