// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppInfo 应用与运行环境信息
 */
export class AppInfo {
    /**
     * Creates a new AppInfo instance.
     * @param {Partial<AppInfo>} [$$source = {}] - The source object to create the AppInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("goVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["goVersion"] = "";
        }
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platform"] = "";
        }
        if (!("arch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppInfo(/** @type {Partial<AppInfo>} */($$parsedSource));
    }
}

/**
 * AppStartupState 应用启动状态。
 * 
 * degraded 表示初始化失败（例如数据库损坏）：界面照常打开并显示原因，
 * 用户可重试初始化，也能靠应用内更新拉一个修复版本——所以这里不用
 * 「启动失败直接退出」的语义。
 */
export class AppStartupState {
    /**
     * Creates a new AppStartupState instance.
     * @param {Partial<AppStartupState>} [$$source = {}] - The source object to create the AppStartupState.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * State initializing / ready / degraded
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * Error 初始化失败原因（degraded 时非空）
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppStartupState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppStartupState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppStartupState(/** @type {Partial<AppStartupState>} */($$parsedSource));
    }
}
